
development:
  adapter: postgresql
  encoding: unicode
  database: Travel_Stories_development
  pool: 5
  host: localhost
  username: angiegove
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: Travel_Stories_test
  pool: 5
  host: localhost
  username: angiegove
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: Travel_Stories_production
  pool: 5
  username: angiegove
  password:
